name: Test Environment Variables 
on:
  push:
    branches: [master]
jobs:
  testing:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world
        run: |
          echo "Hello world"